'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://sledzenie.pocztapolska.pl", ConfigurationName:="ServiceReference1.SledzeniePortType")>  _
    Public Interface SledzeniePortType
        
        'CODEGEN: Generating message contract since the operation wersja is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="urn:wersja", ReplyAction:="urn:wersjaResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function wersja(ByVal request As ServiceReference1.wersjaRequest) As ServiceReference1.wersjaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:wersja", ReplyAction:="urn:wersjaResponse")>  _
        Function wersjaAsync(ByVal request As ServiceReference1.wersjaRequest) As System.Threading.Tasks.Task(Of ServiceReference1.wersjaResponse)
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="urn:sprawdzPrzesylkiPl", ReplyAction:="urn:sprawdzPrzesylkiPlResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function sprawdzPrzesylkiPl(ByVal request As ServiceReference1.sprawdzPrzesylkiPlRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServiceReference1.sprawdzPrzesylkiPlResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:sprawdzPrzesylkiPl", ReplyAction:="urn:sprawdzPrzesylkiPlResponse")>  _
        Function sprawdzPrzesylkiPlAsync(ByVal request As ServiceReference1.sprawdzPrzesylkiPlRequest) As System.Threading.Tasks.Task(Of ServiceReference1.sprawdzPrzesylkiPlResponse)
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="urn:sprawdzPrzesylkePl", ReplyAction:="urn:sprawdzPrzesylkePlResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function sprawdzPrzesylkePl(ByVal request As ServiceReference1.sprawdzPrzesylkePlRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServiceReference1.sprawdzPrzesylkePlResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:sprawdzPrzesylkePl", ReplyAction:="urn:sprawdzPrzesylkePlResponse")>  _
        Function sprawdzPrzesylkePlAsync(ByVal request As ServiceReference1.sprawdzPrzesylkePlRequest) As System.Threading.Tasks.Task(Of ServiceReference1.sprawdzPrzesylkePlResponse)
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="urn:sprawdzPrzesylkiOdDo", ReplyAction:="urn:sprawdzPrzesylkiOdDoResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function sprawdzPrzesylkiOdDo(ByVal request As ServiceReference1.sprawdzPrzesylkiOdDoRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServiceReference1.sprawdzPrzesylkiOdDoResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:sprawdzPrzesylkiOdDo", ReplyAction:="urn:sprawdzPrzesylkiOdDoResponse")>  _
        Function sprawdzPrzesylkiOdDoAsync(ByVal request As ServiceReference1.sprawdzPrzesylkiOdDoRequest) As System.Threading.Tasks.Task(Of ServiceReference1.sprawdzPrzesylkiOdDoResponse)
        
        'CODEGEN: Generating message contract since the operation maksymalnaLiczbaPrzesylek is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="urn:maksymalnaLiczbaPrzesylek", ReplyAction:="urn:maksymalnaLiczbaPrzesylekResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function maksymalnaLiczbaPrzesylek(ByVal request As ServiceReference1.maksymalnaLiczbaPrzesylekRequest) As ServiceReference1.maksymalnaLiczbaPrzesylekResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:maksymalnaLiczbaPrzesylek", ReplyAction:="urn:maksymalnaLiczbaPrzesylekResponse")>  _
        Function maksymalnaLiczbaPrzesylekAsync(ByVal request As ServiceReference1.maksymalnaLiczbaPrzesylekRequest) As System.Threading.Tasks.Task(Of ServiceReference1.maksymalnaLiczbaPrzesylekResponse)
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="urn:sprawdzPrzesylke", ReplyAction:="urn:sprawdzPrzesylkeResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function sprawdzPrzesylke(ByVal request As ServiceReference1.sprawdzPrzesylkeRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServiceReference1.sprawdzPrzesylkeResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:sprawdzPrzesylke", ReplyAction:="urn:sprawdzPrzesylkeResponse")>  _
        Function sprawdzPrzesylkeAsync(ByVal request As ServiceReference1.sprawdzPrzesylkeRequest) As System.Threading.Tasks.Task(Of ServiceReference1.sprawdzPrzesylkeResponse)
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="urn:sprawdzPrzesylkiOdDoPl", ReplyAction:="urn:sprawdzPrzesylkiOdDoPlResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function sprawdzPrzesylkiOdDoPl(ByVal request As ServiceReference1.sprawdzPrzesylkiOdDoPlRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServiceReference1.sprawdzPrzesylkiOdDoPlResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:sprawdzPrzesylkiOdDoPl", ReplyAction:="urn:sprawdzPrzesylkiOdDoPlResponse")>  _
        Function sprawdzPrzesylkiOdDoPlAsync(ByVal request As ServiceReference1.sprawdzPrzesylkiOdDoPlRequest) As System.Threading.Tasks.Task(Of ServiceReference1.sprawdzPrzesylkiOdDoPlResponse)
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="urn:witaj", ReplyAction:="urn:witajResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function witaj(ByVal request As ServiceReference1.witajRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServiceReference1.witajResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:witaj", ReplyAction:="urn:witajResponse")>  _
        Function witajAsync(ByVal request As ServiceReference1.witajRequest) As System.Threading.Tasks.Task(Of ServiceReference1.witajResponse)
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="urn:sprawdzPrzesylki", ReplyAction:="urn:sprawdzPrzesylkiResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function sprawdzPrzesylki(ByVal request As ServiceReference1.sprawdzPrzesylkiRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServiceReference1.sprawdzPrzesylkiResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:sprawdzPrzesylki", ReplyAction:="urn:sprawdzPrzesylkiResponse")>  _
        Function sprawdzPrzesylkiAsync(ByVal request As ServiceReference1.sprawdzPrzesylkiRequest) As System.Threading.Tasks.Task(Of ServiceReference1.sprawdzPrzesylkiResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class wersjaRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="wersjaResponse", WrapperNamespace:="http://sledzenie.pocztapolska.pl", IsWrapped:=true)>  _
    Partial Public Class wersjaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://sledzenie.pocztapolska.pl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ws.sledzenie.pocztapolska.pl/xsd")>  _
    Partial Public Class Komunikat
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private przesylkiField() As Przesylka
        
        Private statusField As Integer
        
        Private statusFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true, Order:=0),  _
         System.Xml.Serialization.XmlArrayItemAttribute("przesylka")>  _
        Public Property przesylki() As Przesylka()
            Get
                Return Me.przesylkiField
            End Get
            Set
                Me.przesylkiField = value
                Me.RaisePropertyChanged("przesylki")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property status() As Integer
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property statusSpecified() As Boolean
            Get
                Return Me.statusFieldSpecified
            End Get
            Set
                Me.statusFieldSpecified = value
                Me.RaisePropertyChanged("statusSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ws.sledzenie.pocztapolska.pl/xsd")>  _
    Partial Public Class Przesylka
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private danePrzesylkiField As DanePrzesylki
        
        Private numerField As String
        
        Private statusField As Integer
        
        Private statusFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property danePrzesylki() As DanePrzesylki
            Get
                Return Me.danePrzesylkiField
            End Get
            Set
                Me.danePrzesylkiField = value
                Me.RaisePropertyChanged("danePrzesylki")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property numer() As String
            Get
                Return Me.numerField
            End Get
            Set
                Me.numerField = value
                Me.RaisePropertyChanged("numer")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property status() As Integer
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property statusSpecified() As Boolean
            Get
                Return Me.statusFieldSpecified
            End Get
            Set
                Me.statusFieldSpecified = value
                Me.RaisePropertyChanged("statusSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ws.sledzenie.pocztapolska.pl/xsd")>  _
    Partial Public Class DanePrzesylki
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private dataNadaniaField As System.Nullable(Of Date)
        
        Private dataNadaniaFieldSpecified As Boolean
        
        Private formatField As String
        
        Private kodKrajuNadaniaField As String
        
        Private kodKrajuPrzeznField As String
        
        Private kodRodzPrzesField As String
        
        Private krajNadaniaField As String
        
        Private krajPrzeznField As String
        
        Private masaField As System.Nullable(Of Single)
        
        Private masaFieldSpecified As Boolean
        
        Private numerField As String
        
        Private proceduraSerwisField As Procedura
        
        Private rodzPrzesField As String
        
        Private urzadNadaniaField As Jednostka
        
        Private urzadPrzeznField As Jednostka
        
        Private zakonczonoObslugeField As Boolean
        
        Private zakonczonoObslugeFieldSpecified As Boolean
        
        Private zdarzeniaField() As Zdarzenie
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date", IsNullable:=true, Order:=0)>  _
        Public Property dataNadania() As System.Nullable(Of Date)
            Get
                Return Me.dataNadaniaField
            End Get
            Set
                Me.dataNadaniaField = value
                Me.RaisePropertyChanged("dataNadania")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property dataNadaniaSpecified() As Boolean
            Get
                Return Me.dataNadaniaFieldSpecified
            End Get
            Set
                Me.dataNadaniaFieldSpecified = value
                Me.RaisePropertyChanged("dataNadaniaSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property format() As String
            Get
                Return Me.formatField
            End Get
            Set
                Me.formatField = value
                Me.RaisePropertyChanged("format")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property kodKrajuNadania() As String
            Get
                Return Me.kodKrajuNadaniaField
            End Get
            Set
                Me.kodKrajuNadaniaField = value
                Me.RaisePropertyChanged("kodKrajuNadania")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=3)>  _
        Public Property kodKrajuPrzezn() As String
            Get
                Return Me.kodKrajuPrzeznField
            End Get
            Set
                Me.kodKrajuPrzeznField = value
                Me.RaisePropertyChanged("kodKrajuPrzezn")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=4)>  _
        Public Property kodRodzPrzes() As String
            Get
                Return Me.kodRodzPrzesField
            End Get
            Set
                Me.kodRodzPrzesField = value
                Me.RaisePropertyChanged("kodRodzPrzes")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=5)>  _
        Public Property krajNadania() As String
            Get
                Return Me.krajNadaniaField
            End Get
            Set
                Me.krajNadaniaField = value
                Me.RaisePropertyChanged("krajNadania")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=6)>  _
        Public Property krajPrzezn() As String
            Get
                Return Me.krajPrzeznField
            End Get
            Set
                Me.krajPrzeznField = value
                Me.RaisePropertyChanged("krajPrzezn")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=7)>  _
        Public Property masa() As System.Nullable(Of Single)
            Get
                Return Me.masaField
            End Get
            Set
                Me.masaField = value
                Me.RaisePropertyChanged("masa")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property masaSpecified() As Boolean
            Get
                Return Me.masaFieldSpecified
            End Get
            Set
                Me.masaFieldSpecified = value
                Me.RaisePropertyChanged("masaSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=8)>  _
        Public Property numer() As String
            Get
                Return Me.numerField
            End Get
            Set
                Me.numerField = value
                Me.RaisePropertyChanged("numer")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=9)>  _
        Public Property proceduraSerwis() As Procedura
            Get
                Return Me.proceduraSerwisField
            End Get
            Set
                Me.proceduraSerwisField = value
                Me.RaisePropertyChanged("proceduraSerwis")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=10)>  _
        Public Property rodzPrzes() As String
            Get
                Return Me.rodzPrzesField
            End Get
            Set
                Me.rodzPrzesField = value
                Me.RaisePropertyChanged("rodzPrzes")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=11)>  _
        Public Property urzadNadania() As Jednostka
            Get
                Return Me.urzadNadaniaField
            End Get
            Set
                Me.urzadNadaniaField = value
                Me.RaisePropertyChanged("urzadNadania")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=12)>  _
        Public Property urzadPrzezn() As Jednostka
            Get
                Return Me.urzadPrzeznField
            End Get
            Set
                Me.urzadPrzeznField = value
                Me.RaisePropertyChanged("urzadPrzezn")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=13)>  _
        Public Property zakonczonoObsluge() As Boolean
            Get
                Return Me.zakonczonoObslugeField
            End Get
            Set
                Me.zakonczonoObslugeField = value
                Me.RaisePropertyChanged("zakonczonoObsluge")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property zakonczonoObslugeSpecified() As Boolean
            Get
                Return Me.zakonczonoObslugeFieldSpecified
            End Get
            Set
                Me.zakonczonoObslugeFieldSpecified = value
                Me.RaisePropertyChanged("zakonczonoObslugeSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true, Order:=14),  _
         System.Xml.Serialization.XmlArrayItemAttribute("zdarzenie")>  _
        Public Property zdarzenia() As Zdarzenie()
            Get
                Return Me.zdarzeniaField
            End Get
            Set
                Me.zdarzeniaField = value
                Me.RaisePropertyChanged("zdarzenia")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ws.sledzenie.pocztapolska.pl/xsd")>  _
    Partial Public Class Procedura
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private kodField As String
        
        Private kopertaFirmowaField As String
        
        Private nazwaField As String
        
        Private przesylkiPowiazaneField() As PrzesylkaPowiazana
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property kod() As String
            Get
                Return Me.kodField
            End Get
            Set
                Me.kodField = value
                Me.RaisePropertyChanged("kod")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property kopertaFirmowa() As String
            Get
                Return Me.kopertaFirmowaField
            End Get
            Set
                Me.kopertaFirmowaField = value
                Me.RaisePropertyChanged("kopertaFirmowa")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property nazwa() As String
            Get
                Return Me.nazwaField
            End Get
            Set
                Me.nazwaField = value
                Me.RaisePropertyChanged("nazwa")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true, Order:=3),  _
         System.Xml.Serialization.XmlArrayItemAttribute("przesylkaPowiazana")>  _
        Public Property przesylkiPowiazane() As PrzesylkaPowiazana()
            Get
                Return Me.przesylkiPowiazaneField
            End Get
            Set
                Me.przesylkiPowiazaneField = value
                Me.RaisePropertyChanged("przesylkiPowiazane")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ws.sledzenie.pocztapolska.pl/xsd")>  _
    Partial Public Class PrzesylkaPowiazana
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private nrPrzesylkiPowiazanejField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property nrPrzesylkiPowiazanej() As String
            Get
                Return Me.nrPrzesylkiPowiazanejField
            End Get
            Set
                Me.nrPrzesylkiPowiazanejField = value
                Me.RaisePropertyChanged("nrPrzesylkiPowiazanej")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ws.sledzenie.pocztapolska.pl/xsd")>  _
    Partial Public Class Przyczyna
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private kodField As String
        
        Private nazwaField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property kod() As String
            Get
                Return Me.kodField
            End Get
            Set
                Me.kodField = value
                Me.RaisePropertyChanged("kod")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property nazwa() As String
            Get
                Return Me.nazwaField
            End Get
            Set
                Me.nazwaField = value
                Me.RaisePropertyChanged("nazwa")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ws.sledzenie.pocztapolska.pl/xsd")>  _
    Partial Public Class Zdarzenie
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private czasField As String
        
        Private jednostkaField As Jednostka
        
        Private kodField As String
        
        Private konczaceField As Boolean
        
        Private konczaceFieldSpecified As Boolean
        
        Private nazwaField As String
        
        Private przyczynaField As Przyczyna
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property czas() As String
            Get
                Return Me.czasField
            End Get
            Set
                Me.czasField = value
                Me.RaisePropertyChanged("czas")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property jednostka() As Jednostka
            Get
                Return Me.jednostkaField
            End Get
            Set
                Me.jednostkaField = value
                Me.RaisePropertyChanged("jednostka")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property kod() As String
            Get
                Return Me.kodField
            End Get
            Set
                Me.kodField = value
                Me.RaisePropertyChanged("kod")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property konczace() As Boolean
            Get
                Return Me.konczaceField
            End Get
            Set
                Me.konczaceField = value
                Me.RaisePropertyChanged("konczace")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property konczaceSpecified() As Boolean
            Get
                Return Me.konczaceFieldSpecified
            End Get
            Set
                Me.konczaceFieldSpecified = value
                Me.RaisePropertyChanged("konczaceSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=4)>  _
        Public Property nazwa() As String
            Get
                Return Me.nazwaField
            End Get
            Set
                Me.nazwaField = value
                Me.RaisePropertyChanged("nazwa")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=5)>  _
        Public Property przyczyna() As Przyczyna
            Get
                Return Me.przyczynaField
            End Get
            Set
                Me.przyczynaField = value
                Me.RaisePropertyChanged("przyczyna")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ws.sledzenie.pocztapolska.pl/xsd")>  _
    Partial Public Class Jednostka
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private daneSzczegoloweField As SzczDaneJednostki
        
        Private nazwaField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property daneSzczegolowe() As SzczDaneJednostki
            Get
                Return Me.daneSzczegoloweField
            End Get
            Set
                Me.daneSzczegoloweField = value
                Me.RaisePropertyChanged("daneSzczegolowe")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property nazwa() As String
            Get
                Return Me.nazwaField
            End Get
            Set
                Me.nazwaField = value
                Me.RaisePropertyChanged("nazwa")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ws.sledzenie.pocztapolska.pl/xsd")>  _
    Partial Public Class SzczDaneJednostki
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private dlGeogrField As Single
        
        Private dlGeogrFieldSpecified As Boolean
        
        Private godzinyPracyField As GodzinyPracy
        
        Private miejscowoscField As String
        
        Private nrDomuField As String
        
        Private nrLokaluField As String
        
        Private pnaField As String
        
        Private szerGeogrField As Single
        
        Private szerGeogrFieldSpecified As Boolean
        
        Private ulicaField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property dlGeogr() As Single
            Get
                Return Me.dlGeogrField
            End Get
            Set
                Me.dlGeogrField = value
                Me.RaisePropertyChanged("dlGeogr")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property dlGeogrSpecified() As Boolean
            Get
                Return Me.dlGeogrFieldSpecified
            End Get
            Set
                Me.dlGeogrFieldSpecified = value
                Me.RaisePropertyChanged("dlGeogrSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property godzinyPracy() As GodzinyPracy
            Get
                Return Me.godzinyPracyField
            End Get
            Set
                Me.godzinyPracyField = value
                Me.RaisePropertyChanged("godzinyPracy")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property miejscowosc() As String
            Get
                Return Me.miejscowoscField
            End Get
            Set
                Me.miejscowoscField = value
                Me.RaisePropertyChanged("miejscowosc")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=3)>  _
        Public Property nrDomu() As String
            Get
                Return Me.nrDomuField
            End Get
            Set
                Me.nrDomuField = value
                Me.RaisePropertyChanged("nrDomu")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=4)>  _
        Public Property nrLokalu() As String
            Get
                Return Me.nrLokaluField
            End Get
            Set
                Me.nrLokaluField = value
                Me.RaisePropertyChanged("nrLokalu")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=5)>  _
        Public Property pna() As String
            Get
                Return Me.pnaField
            End Get
            Set
                Me.pnaField = value
                Me.RaisePropertyChanged("pna")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property szerGeogr() As Single
            Get
                Return Me.szerGeogrField
            End Get
            Set
                Me.szerGeogrField = value
                Me.RaisePropertyChanged("szerGeogr")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property szerGeogrSpecified() As Boolean
            Get
                Return Me.szerGeogrFieldSpecified
            End Get
            Set
                Me.szerGeogrFieldSpecified = value
                Me.RaisePropertyChanged("szerGeogrSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=7)>  _
        Public Property ulica() As String
            Get
                Return Me.ulicaField
            End Get
            Set
                Me.ulicaField = value
                Me.RaisePropertyChanged("ulica")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ws.sledzenie.pocztapolska.pl/xsd")>  _
    Partial Public Class GodzinyPracy
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private dniRoboczeField As GodzinyZUwagami
        
        Private niedzISwField As GodzinyZUwagami
        
        Private sobotyField As GodzinyZUwagami
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property dniRobocze() As GodzinyZUwagami
            Get
                Return Me.dniRoboczeField
            End Get
            Set
                Me.dniRoboczeField = value
                Me.RaisePropertyChanged("dniRobocze")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property niedzISw() As GodzinyZUwagami
            Get
                Return Me.niedzISwField
            End Get
            Set
                Me.niedzISwField = value
                Me.RaisePropertyChanged("niedzISw")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property soboty() As GodzinyZUwagami
            Get
                Return Me.sobotyField
            End Get
            Set
                Me.sobotyField = value
                Me.RaisePropertyChanged("soboty")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ws.sledzenie.pocztapolska.pl/xsd")>  _
    Partial Public Class GodzinyZUwagami
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private godzinyField As String
        
        Private uwagiField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property godziny() As String
            Get
                Return Me.godzinyField
            End Get
            Set
                Me.godzinyField = value
                Me.RaisePropertyChanged("godziny")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property uwagi() As String
            Get
                Return Me.uwagiField
            End Get
            Set
                Me.uwagiField = value
                Me.RaisePropertyChanged("uwagi")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="sprawdzPrzesylkiPl", WrapperNamespace:="http://sledzenie.pocztapolska.pl", IsWrapped:=true)>  _
    Partial Public Class sprawdzPrzesylkiPlRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://sledzenie.pocztapolska.pl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("numer", IsNullable:=true)>  _
        Public numer() As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal numer() As String)
            MyBase.New
            Me.numer = numer
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="sprawdzPrzesylkiPlResponse", WrapperNamespace:="http://sledzenie.pocztapolska.pl", IsWrapped:=true)>  _
    Partial Public Class sprawdzPrzesylkiPlResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://sledzenie.pocztapolska.pl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public [return] As ServiceReference1.Komunikat
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As ServiceReference1.Komunikat)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="sprawdzPrzesylkePl", WrapperNamespace:="http://sledzenie.pocztapolska.pl", IsWrapped:=true)>  _
    Partial Public Class sprawdzPrzesylkePlRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://sledzenie.pocztapolska.pl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public numer As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal numer As String)
            MyBase.New
            Me.numer = numer
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="sprawdzPrzesylkePlResponse", WrapperNamespace:="http://sledzenie.pocztapolska.pl", IsWrapped:=true)>  _
    Partial Public Class sprawdzPrzesylkePlResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://sledzenie.pocztapolska.pl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public [return] As ServiceReference1.Przesylka
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As ServiceReference1.Przesylka)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="sprawdzPrzesylkiOdDo", WrapperNamespace:="http://sledzenie.pocztapolska.pl", IsWrapped:=true)>  _
    Partial Public Class sprawdzPrzesylkiOdDoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://sledzenie.pocztapolska.pl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("numer", IsNullable:=true)>  _
        Public numer() As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://sledzenie.pocztapolska.pl", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public odDnia As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://sledzenie.pocztapolska.pl", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public doDnia As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal numer() As String, ByVal odDnia As String, ByVal doDnia As String)
            MyBase.New
            Me.numer = numer
            Me.odDnia = odDnia
            Me.doDnia = doDnia
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="sprawdzPrzesylkiOdDoResponse", WrapperNamespace:="http://sledzenie.pocztapolska.pl", IsWrapped:=true)>  _
    Partial Public Class sprawdzPrzesylkiOdDoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://sledzenie.pocztapolska.pl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public [return] As ServiceReference1.Komunikat
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As ServiceReference1.Komunikat)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class maksymalnaLiczbaPrzesylekRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="maksymalnaLiczbaPrzesylekResponse", WrapperNamespace:="http://sledzenie.pocztapolska.pl", IsWrapped:=true)>  _
    Partial Public Class maksymalnaLiczbaPrzesylekResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://sledzenie.pocztapolska.pl", Order:=0)>  _
        Public [return] As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Integer)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="sprawdzPrzesylke", WrapperNamespace:="http://sledzenie.pocztapolska.pl", IsWrapped:=true)>  _
    Partial Public Class sprawdzPrzesylkeRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://sledzenie.pocztapolska.pl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public numer As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal numer As String)
            MyBase.New
            Me.numer = numer
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="sprawdzPrzesylkeResponse", WrapperNamespace:="http://sledzenie.pocztapolska.pl", IsWrapped:=true)>  _
    Partial Public Class sprawdzPrzesylkeResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://sledzenie.pocztapolska.pl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public [return] As ServiceReference1.Przesylka
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As ServiceReference1.Przesylka)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="sprawdzPrzesylkiOdDoPl", WrapperNamespace:="http://sledzenie.pocztapolska.pl", IsWrapped:=true)>  _
    Partial Public Class sprawdzPrzesylkiOdDoPlRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://sledzenie.pocztapolska.pl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("numer", IsNullable:=true)>  _
        Public numer() As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://sledzenie.pocztapolska.pl", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public odDnia As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://sledzenie.pocztapolska.pl", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public doDnia As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal numer() As String, ByVal odDnia As String, ByVal doDnia As String)
            MyBase.New
            Me.numer = numer
            Me.odDnia = odDnia
            Me.doDnia = doDnia
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="sprawdzPrzesylkiOdDoPlResponse", WrapperNamespace:="http://sledzenie.pocztapolska.pl", IsWrapped:=true)>  _
    Partial Public Class sprawdzPrzesylkiOdDoPlResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://sledzenie.pocztapolska.pl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public [return] As ServiceReference1.Komunikat
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As ServiceReference1.Komunikat)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="witaj", WrapperNamespace:="http://sledzenie.pocztapolska.pl", IsWrapped:=true)>  _
    Partial Public Class witajRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://sledzenie.pocztapolska.pl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public imie As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal imie As String)
            MyBase.New
            Me.imie = imie
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="witajResponse", WrapperNamespace:="http://sledzenie.pocztapolska.pl", IsWrapped:=true)>  _
    Partial Public Class witajResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://sledzenie.pocztapolska.pl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="sprawdzPrzesylki", WrapperNamespace:="http://sledzenie.pocztapolska.pl", IsWrapped:=true)>  _
    Partial Public Class sprawdzPrzesylkiRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://sledzenie.pocztapolska.pl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("numer", IsNullable:=true)>  _
        Public numer() As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal numer() As String)
            MyBase.New
            Me.numer = numer
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="sprawdzPrzesylkiResponse", WrapperNamespace:="http://sledzenie.pocztapolska.pl", IsWrapped:=true)>  _
    Partial Public Class sprawdzPrzesylkiResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://sledzenie.pocztapolska.pl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public [return] As ServiceReference1.Komunikat
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As ServiceReference1.Komunikat)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface SledzeniePortTypeChannel
        Inherits ServiceReference1.SledzeniePortType, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SledzeniePortTypeClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.SledzeniePortType)
        Implements ServiceReference1.SledzeniePortType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_SledzeniePortType_wersja(ByVal request As ServiceReference1.wersjaRequest) As ServiceReference1.wersjaResponse Implements ServiceReference1.SledzeniePortType.wersja
            Return MyBase.Channel.wersja(request)
        End Function
        
        Public Function wersja() As String
            Dim inValue As ServiceReference1.wersjaRequest = New ServiceReference1.wersjaRequest()
            Dim retVal As ServiceReference1.wersjaResponse = CType(Me,ServiceReference1.SledzeniePortType).wersja(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_SledzeniePortType_wersjaAsync(ByVal request As ServiceReference1.wersjaRequest) As System.Threading.Tasks.Task(Of ServiceReference1.wersjaResponse) Implements ServiceReference1.SledzeniePortType.wersjaAsync
            Return MyBase.Channel.wersjaAsync(request)
        End Function
        
        Public Function wersjaAsync() As System.Threading.Tasks.Task(Of ServiceReference1.wersjaResponse)
            Dim inValue As ServiceReference1.wersjaRequest = New ServiceReference1.wersjaRequest()
            Return CType(Me,ServiceReference1.SledzeniePortType).wersjaAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_SledzeniePortType_sprawdzPrzesylkiPl(ByVal request As ServiceReference1.sprawdzPrzesylkiPlRequest) As ServiceReference1.sprawdzPrzesylkiPlResponse Implements ServiceReference1.SledzeniePortType.sprawdzPrzesylkiPl
            Return MyBase.Channel.sprawdzPrzesylkiPl(request)
        End Function
        
        Public Function sprawdzPrzesylkiPl(ByVal numer() As String) As ServiceReference1.Komunikat
            Dim inValue As ServiceReference1.sprawdzPrzesylkiPlRequest = New ServiceReference1.sprawdzPrzesylkiPlRequest()
            inValue.numer = numer
            Dim retVal As ServiceReference1.sprawdzPrzesylkiPlResponse = CType(Me,ServiceReference1.SledzeniePortType).sprawdzPrzesylkiPl(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_SledzeniePortType_sprawdzPrzesylkiPlAsync(ByVal request As ServiceReference1.sprawdzPrzesylkiPlRequest) As System.Threading.Tasks.Task(Of ServiceReference1.sprawdzPrzesylkiPlResponse) Implements ServiceReference1.SledzeniePortType.sprawdzPrzesylkiPlAsync
            Return MyBase.Channel.sprawdzPrzesylkiPlAsync(request)
        End Function
        
        Public Function sprawdzPrzesylkiPlAsync(ByVal numer() As String) As System.Threading.Tasks.Task(Of ServiceReference1.sprawdzPrzesylkiPlResponse)
            Dim inValue As ServiceReference1.sprawdzPrzesylkiPlRequest = New ServiceReference1.sprawdzPrzesylkiPlRequest()
            inValue.numer = numer
            Return CType(Me,ServiceReference1.SledzeniePortType).sprawdzPrzesylkiPlAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_SledzeniePortType_sprawdzPrzesylkePl(ByVal request As ServiceReference1.sprawdzPrzesylkePlRequest) As ServiceReference1.sprawdzPrzesylkePlResponse Implements ServiceReference1.SledzeniePortType.sprawdzPrzesylkePl
            Return MyBase.Channel.sprawdzPrzesylkePl(request)
        End Function
        
        Public Function sprawdzPrzesylkePl(ByVal numer As String) As ServiceReference1.Przesylka
            Dim inValue As ServiceReference1.sprawdzPrzesylkePlRequest = New ServiceReference1.sprawdzPrzesylkePlRequest()
            inValue.numer = numer
            Dim retVal As ServiceReference1.sprawdzPrzesylkePlResponse = CType(Me,ServiceReference1.SledzeniePortType).sprawdzPrzesylkePl(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_SledzeniePortType_sprawdzPrzesylkePlAsync(ByVal request As ServiceReference1.sprawdzPrzesylkePlRequest) As System.Threading.Tasks.Task(Of ServiceReference1.sprawdzPrzesylkePlResponse) Implements ServiceReference1.SledzeniePortType.sprawdzPrzesylkePlAsync
            Return MyBase.Channel.sprawdzPrzesylkePlAsync(request)
        End Function
        
        Public Function sprawdzPrzesylkePlAsync(ByVal numer As String) As System.Threading.Tasks.Task(Of ServiceReference1.sprawdzPrzesylkePlResponse)
            Dim inValue As ServiceReference1.sprawdzPrzesylkePlRequest = New ServiceReference1.sprawdzPrzesylkePlRequest()
            inValue.numer = numer
            Return CType(Me,ServiceReference1.SledzeniePortType).sprawdzPrzesylkePlAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_SledzeniePortType_sprawdzPrzesylkiOdDo(ByVal request As ServiceReference1.sprawdzPrzesylkiOdDoRequest) As ServiceReference1.sprawdzPrzesylkiOdDoResponse Implements ServiceReference1.SledzeniePortType.sprawdzPrzesylkiOdDo
            Return MyBase.Channel.sprawdzPrzesylkiOdDo(request)
        End Function
        
        Public Function sprawdzPrzesylkiOdDo(ByVal numer() As String, ByVal odDnia As String, ByVal doDnia As String) As ServiceReference1.Komunikat
            Dim inValue As ServiceReference1.sprawdzPrzesylkiOdDoRequest = New ServiceReference1.sprawdzPrzesylkiOdDoRequest()
            inValue.numer = numer
            inValue.odDnia = odDnia
            inValue.doDnia = doDnia
            Dim retVal As ServiceReference1.sprawdzPrzesylkiOdDoResponse = CType(Me,ServiceReference1.SledzeniePortType).sprawdzPrzesylkiOdDo(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_SledzeniePortType_sprawdzPrzesylkiOdDoAsync(ByVal request As ServiceReference1.sprawdzPrzesylkiOdDoRequest) As System.Threading.Tasks.Task(Of ServiceReference1.sprawdzPrzesylkiOdDoResponse) Implements ServiceReference1.SledzeniePortType.sprawdzPrzesylkiOdDoAsync
            Return MyBase.Channel.sprawdzPrzesylkiOdDoAsync(request)
        End Function
        
        Public Function sprawdzPrzesylkiOdDoAsync(ByVal numer() As String, ByVal odDnia As String, ByVal doDnia As String) As System.Threading.Tasks.Task(Of ServiceReference1.sprawdzPrzesylkiOdDoResponse)
            Dim inValue As ServiceReference1.sprawdzPrzesylkiOdDoRequest = New ServiceReference1.sprawdzPrzesylkiOdDoRequest()
            inValue.numer = numer
            inValue.odDnia = odDnia
            inValue.doDnia = doDnia
            Return CType(Me,ServiceReference1.SledzeniePortType).sprawdzPrzesylkiOdDoAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_SledzeniePortType_maksymalnaLiczbaPrzesylek(ByVal request As ServiceReference1.maksymalnaLiczbaPrzesylekRequest) As ServiceReference1.maksymalnaLiczbaPrzesylekResponse Implements ServiceReference1.SledzeniePortType.maksymalnaLiczbaPrzesylek
            Return MyBase.Channel.maksymalnaLiczbaPrzesylek(request)
        End Function
        
        Public Function maksymalnaLiczbaPrzesylek() As Integer
            Dim inValue As ServiceReference1.maksymalnaLiczbaPrzesylekRequest = New ServiceReference1.maksymalnaLiczbaPrzesylekRequest()
            Dim retVal As ServiceReference1.maksymalnaLiczbaPrzesylekResponse = CType(Me,ServiceReference1.SledzeniePortType).maksymalnaLiczbaPrzesylek(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_SledzeniePortType_maksymalnaLiczbaPrzesylekAsync(ByVal request As ServiceReference1.maksymalnaLiczbaPrzesylekRequest) As System.Threading.Tasks.Task(Of ServiceReference1.maksymalnaLiczbaPrzesylekResponse) Implements ServiceReference1.SledzeniePortType.maksymalnaLiczbaPrzesylekAsync
            Return MyBase.Channel.maksymalnaLiczbaPrzesylekAsync(request)
        End Function
        
        Public Function maksymalnaLiczbaPrzesylekAsync() As System.Threading.Tasks.Task(Of ServiceReference1.maksymalnaLiczbaPrzesylekResponse)
            Dim inValue As ServiceReference1.maksymalnaLiczbaPrzesylekRequest = New ServiceReference1.maksymalnaLiczbaPrzesylekRequest()
            Return CType(Me,ServiceReference1.SledzeniePortType).maksymalnaLiczbaPrzesylekAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_SledzeniePortType_sprawdzPrzesylke(ByVal request As ServiceReference1.sprawdzPrzesylkeRequest) As ServiceReference1.sprawdzPrzesylkeResponse Implements ServiceReference1.SledzeniePortType.sprawdzPrzesylke
            Return MyBase.Channel.sprawdzPrzesylke(request)
        End Function
        
        Public Function sprawdzPrzesylke(ByVal numer As String) As ServiceReference1.Przesylka
            Dim inValue As ServiceReference1.sprawdzPrzesylkeRequest = New ServiceReference1.sprawdzPrzesylkeRequest()
            inValue.numer = numer
            Dim retVal As ServiceReference1.sprawdzPrzesylkeResponse = CType(Me,ServiceReference1.SledzeniePortType).sprawdzPrzesylke(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_SledzeniePortType_sprawdzPrzesylkeAsync(ByVal request As ServiceReference1.sprawdzPrzesylkeRequest) As System.Threading.Tasks.Task(Of ServiceReference1.sprawdzPrzesylkeResponse) Implements ServiceReference1.SledzeniePortType.sprawdzPrzesylkeAsync
            Return MyBase.Channel.sprawdzPrzesylkeAsync(request)
        End Function
        
        Public Function sprawdzPrzesylkeAsync(ByVal numer As String) As System.Threading.Tasks.Task(Of ServiceReference1.sprawdzPrzesylkeResponse)
            Dim inValue As ServiceReference1.sprawdzPrzesylkeRequest = New ServiceReference1.sprawdzPrzesylkeRequest()
            inValue.numer = numer
            Return CType(Me,ServiceReference1.SledzeniePortType).sprawdzPrzesylkeAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_SledzeniePortType_sprawdzPrzesylkiOdDoPl(ByVal request As ServiceReference1.sprawdzPrzesylkiOdDoPlRequest) As ServiceReference1.sprawdzPrzesylkiOdDoPlResponse Implements ServiceReference1.SledzeniePortType.sprawdzPrzesylkiOdDoPl
            Return MyBase.Channel.sprawdzPrzesylkiOdDoPl(request)
        End Function
        
        Public Function sprawdzPrzesylkiOdDoPl(ByVal numer() As String, ByVal odDnia As String, ByVal doDnia As String) As ServiceReference1.Komunikat
            Dim inValue As ServiceReference1.sprawdzPrzesylkiOdDoPlRequest = New ServiceReference1.sprawdzPrzesylkiOdDoPlRequest()
            inValue.numer = numer
            inValue.odDnia = odDnia
            inValue.doDnia = doDnia
            Dim retVal As ServiceReference1.sprawdzPrzesylkiOdDoPlResponse = CType(Me,ServiceReference1.SledzeniePortType).sprawdzPrzesylkiOdDoPl(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_SledzeniePortType_sprawdzPrzesylkiOdDoPlAsync(ByVal request As ServiceReference1.sprawdzPrzesylkiOdDoPlRequest) As System.Threading.Tasks.Task(Of ServiceReference1.sprawdzPrzesylkiOdDoPlResponse) Implements ServiceReference1.SledzeniePortType.sprawdzPrzesylkiOdDoPlAsync
            Return MyBase.Channel.sprawdzPrzesylkiOdDoPlAsync(request)
        End Function
        
        Public Function sprawdzPrzesylkiOdDoPlAsync(ByVal numer() As String, ByVal odDnia As String, ByVal doDnia As String) As System.Threading.Tasks.Task(Of ServiceReference1.sprawdzPrzesylkiOdDoPlResponse)
            Dim inValue As ServiceReference1.sprawdzPrzesylkiOdDoPlRequest = New ServiceReference1.sprawdzPrzesylkiOdDoPlRequest()
            inValue.numer = numer
            inValue.odDnia = odDnia
            inValue.doDnia = doDnia
            Return CType(Me,ServiceReference1.SledzeniePortType).sprawdzPrzesylkiOdDoPlAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_SledzeniePortType_witaj(ByVal request As ServiceReference1.witajRequest) As ServiceReference1.witajResponse Implements ServiceReference1.SledzeniePortType.witaj
            Return MyBase.Channel.witaj(request)
        End Function
        
        Public Function witaj(ByVal imie As String) As String
            Dim inValue As ServiceReference1.witajRequest = New ServiceReference1.witajRequest()
            inValue.imie = imie
            Dim retVal As ServiceReference1.witajResponse = CType(Me,ServiceReference1.SledzeniePortType).witaj(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_SledzeniePortType_witajAsync(ByVal request As ServiceReference1.witajRequest) As System.Threading.Tasks.Task(Of ServiceReference1.witajResponse) Implements ServiceReference1.SledzeniePortType.witajAsync
            Return MyBase.Channel.witajAsync(request)
        End Function
        
        Public Function witajAsync(ByVal imie As String) As System.Threading.Tasks.Task(Of ServiceReference1.witajResponse)
            Dim inValue As ServiceReference1.witajRequest = New ServiceReference1.witajRequest()
            inValue.imie = imie
            Return CType(Me,ServiceReference1.SledzeniePortType).witajAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_SledzeniePortType_sprawdzPrzesylki(ByVal request As ServiceReference1.sprawdzPrzesylkiRequest) As ServiceReference1.sprawdzPrzesylkiResponse Implements ServiceReference1.SledzeniePortType.sprawdzPrzesylki
            Return MyBase.Channel.sprawdzPrzesylki(request)
        End Function
        
        Public Function sprawdzPrzesylki(ByVal numer() As String) As ServiceReference1.Komunikat
            Dim inValue As ServiceReference1.sprawdzPrzesylkiRequest = New ServiceReference1.sprawdzPrzesylkiRequest()
            inValue.numer = numer
            Dim retVal As ServiceReference1.sprawdzPrzesylkiResponse = CType(Me,ServiceReference1.SledzeniePortType).sprawdzPrzesylki(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_SledzeniePortType_sprawdzPrzesylkiAsync(ByVal request As ServiceReference1.sprawdzPrzesylkiRequest) As System.Threading.Tasks.Task(Of ServiceReference1.sprawdzPrzesylkiResponse) Implements ServiceReference1.SledzeniePortType.sprawdzPrzesylkiAsync
            Return MyBase.Channel.sprawdzPrzesylkiAsync(request)
        End Function
        
        Public Function sprawdzPrzesylkiAsync(ByVal numer() As String) As System.Threading.Tasks.Task(Of ServiceReference1.sprawdzPrzesylkiResponse)
            Dim inValue As ServiceReference1.sprawdzPrzesylkiRequest = New ServiceReference1.sprawdzPrzesylkiRequest()
            inValue.numer = numer
            Return CType(Me,ServiceReference1.SledzeniePortType).sprawdzPrzesylkiAsync(inValue)
        End Function
    End Class
End Namespace
